### ISSUE TITLE
Failed compilation with coq.dev (via opam)

### ISSUE THREAD

**Issue by elfi** [coq-io/io#2]
<pre>
[elf@elfi ~]$ opam repo
  30 [http]  coq-core-dev     https://coq.inria.fr/opam/core-dev
  20 [http]  coq-extra-dev     https://coq.inria.fr/opam/extra-dev
  10 [http]  coq-released     https://coq.inria.fr/opam/released
   0 [http]     default     https://opam.ocaml.org
[elf@elfi ~]$ coqc --version
The Coq Proof Assistant, version trunk (July 2015)
compiled on Jul 2 2015 22:14:56 with OCaml 4.02.1
[elf@elfi ~]$ opam install coq:io
The following actions will be performed:
 - install   coq:io.dev
=== + 1 ===

=-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[coq:io] Fetching https://github.com/coq-io/io

=-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
Building coq:io.dev:
  ./configure.sh
  make -j1
  make install
[ERROR] The compilation of coq:io.dev failed.
Removing coq:io.dev.
  rm -R /Users/elf/.opam/4.02.1/lib/coq/user-contrib/Io

#=== ERROR while installing coq:io.dev ========================================#
# opam-version 1.2.0
# os           darwin
# command      make -j1
# path         /Users/elf/.opam/4.02.1/build/coq:io.dev
# compiler     4.02.1
# exit-code    2
# env-file     /Users/elf/.opam/4.02.1/build/coq:io.dev/coq:io-41873-05296d.env
# stdout-file  /Users/elf/.opam/4.02.1/build/coq:io.dev/coq:io-41873-05296d.out
# stderr-file  /Users/elf/.opam/4.02.1/build/coq:io.dev/coq:io-41873-05296d.err
### stdout ###
# "coqdep" -c -R "src" Io "src/All.v" > "src/All.v.d" || ( RV=$?; rm -f "src/All.v.d"; exit ${RV} )
# "coqdep" -c -R "src" Io "src/C.v" > "src/C.v.d" || ( RV=$?; rm -f "src/C.v.d"; exit ${RV} )
# "coqdep" -c -R "src" Io "src/Effect.v" > "src/Effect.v.d" || ( RV=$?; rm -f "src/Effect.v.d"; exit ${RV} )
# "coqdep" -c -R "src" Io "src/Run.v" > "src/Run.v.d" || ( RV=$?; rm -f "src/Run.v.d"; exit ${RV} )
# "coqc"  -q  -R "src" Io   src/Effect
# "coqc"  -q  -R "src" Io   src/C
### stderr ###
# File "./src/C.v", line 86, characters 2-316:
# Error: Illegal application:
# The term "t" of type "Effect.t -> Type -> Type"
# cannot be applied to the terms
#  "E" : "Effect.t"
#  "T" : "Type"
# The 2nd term has type "Type@{Io.C.1}" which should be coercible to
#  "Type@{Io.C.14}".
# make: *** [src/C.vo] Error 1

[elf@elfi ~]$
</pre>

**Comment by clarus** [comment]
Hi,

To be sure that it compiles, you should use a  stable version of Coq.io instead. You can force the version number:

```
opam install coq:io.3.1.0
```

or remove the repository with development versions:

```
opam repo remove coq-extra-dev
```

The `.dev` version is currently written using Coq `8.4.6`.
